Review
konopat/stellar-burgers pull request #1
Opened 2024-11-22 11:46 UTC by konopat

2024-11-22 13:43 UTC, aromanovnik requested changes
Добрый день, Роман!

Работа выполнена очень хорошо: конструктор бургеров работает без сбоев, оформить заказ может только авторизованный пользователь, запросы к серверу корректно выполняются через хук useEffect, управление модальными окнами — как с данными ингредиента, так и с информацией о заказах из ленты и истории заказов — реализовано с использованием роутинга. Видно хорошее понимание Redux, код выглядит чисто и аккуратно.

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

Что нужно исправить:
* Роуты `/login`, `/register`, `/forgot-password` и `/reset-password` должны быть недоступны для авторизованных пользователей. Авторизованный пользователь при попытке перейти на эти страницы должен быть перенаправлен на главную страницу или страницу профиля.
* После успешной авторизации должно происходить перенаправление на тот маршрут, который пользователь пытался посетить ранее.
* Ссылка должна оставаться активной, если пользователь находится на вложенных маршрутах. 

Что можно улучшить:
* Правильнее делать отдельные селекторы, чтобы изолировать логику доступа к данным состояния и избежать дублирования кода при доступе к данным в разных частях приложения.

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-11-22 13:43 UTC, aromanovnik commented on src/components/ui/app-header/app-header.tsx
> +            [styles.link_active]: location.pathname === '/profile'
**Надо исправить**: Ссылка должна оставаться активной, если пользователь находится на вложенных  маршрутах.  Рекомендуется использовать "dynamic className" - когда `className` передается как функция, которая принимает параметры и возвращает строку с классами.

<img width="1316" alt="Screenshot 2024-11-22 at 15 40 18" src="https://github.com/user-attachments/assets/66ca706d-071d-428e-a899-1e3e1f71ae5d">

2024-11-22 13:43 UTC, aromanovnik commented on src/components/protected-route/index.tsx
> +export const ProtectedRoute: FC<IProtectedRouteProps> = ({
**Надо исправить**: Роуты `/login`, `/register`, `/forgot-password` и `/reset-password` должны быть недоступны для авторизованных пользователей. Авторизованный пользователь при попытке перейти на эти страницы должен быть перенаправлен на главную страницу или страницу профиля.

<img width="1131" alt="Screenshot 2024-11-22 at 15 50 43" src="https://github.com/user-attachments/assets/747861ac-e68d-4500-a01e-657da8d77802">

2024-11-22 13:43 UTC, aromanovnik commented on src/components/protected-route/index.tsx
> +  // Если маршрут защищён и пользователь не авторизован
**Надо исправить**: После успешной авторизации должно происходить перенаправление на тот маршрут, который пользователь пытался посетить ранее.

2024-11-22 13:43 UTC, aromanovnik commented on src/components/protected-route/index.tsx
> +  const { user, isChecked, isLoading } = useAppSelector(
**Можно лучше**: Правильнее делать отдельные селекторы, чтобы изолировать логику доступа к данным состояния и избежать дублирования кода при доступе к данным в разных частях приложения. Это также позволяет легче изменять структуру состояния в будущем без необходимости вносить изменения во множество компонентов.

2024-11-23 05:31 UTC, konopat commented on src/components/protected-route/index.tsx
> +  const { user, isChecked, isLoading } = useAppSelector(
Спасибо за подсказку с селекторами! Исправил, вроде, везде. Код стал действительно понятнее.

2024-11-23 14:04 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2025-01-31 04:34 UTC, closed without merging